"""Public DB surface — a thin facade over the split `_common` /
`_sessions` / `_messages` / `_tags` modules. Callers keep using
`from bearings.db import store` + `store.create_session(...)` and
`store.attach_tag(...)`; the implementation lives in the sibling
modules one layer down.

This file is deliberately a re-export wall. Do not grow it with new
logic — add new functions to whichever `_*.py` module owns the
concern, then re-export here.
"""

from __future__ import annotations

from bearings.db._artifacts import (
    create_artifact,
    delete_artifact,
    get_artifact,
    list_artifacts,
)
from bearings.db._checklists import (
    create_checklist,
    create_item,
    delete_item,
    get_checklist,
    get_item,
    get_item_by_chat_session,
    is_checklist_complete,
    reorder_items,
    set_item_chat_session,
    toggle_item,
    update_checklist,
    update_item,
)
from bearings.db._checkpoints import (
    create_checkpoint,
    delete_checkpoint,
    get_checkpoint,
    list_checkpoints,
)
from bearings.db._common import MIGRATIONS_DIR, init_db
from bearings.db._messages import (
    append_tool_output,
    attach_tool_calls_to_message,
    find_replayable_prompt,
    finish_tool_call,
    get_latest_todowrite,
    get_session_token_totals,
    insert_message,
    insert_tool_call_start,
    list_all_messages,
    list_all_tool_calls,
    list_messages,
    list_tool_calls,
    mark_replay_attempted,
    search_messages,
    update_message_flags,
)
from bearings.db._reorg import (
    MoveResult,
    ReorgOp,
    delete_reorg_audit,
    detect_tool_call_group_warnings,
    list_reorg_audits,
    move_messages_tx,
    record_reorg_audit,
)
from bearings.db._sessions import (
    add_session_cost,
    close_session,
    create_session,
    delete_session,
    get_session,
    import_session,
    list_all_sessions,
    list_sessions,
    mark_session_completed,
    mark_session_viewed,
    reopen_if_closed,
    reopen_session,
    set_sdk_session_id,
    set_session_context_usage,
    set_session_permission_mode,
    touch_session,
    update_session,
)
from bearings.db._tags import (
    attach_tag,
    create_tag,
    delete_tag,
    delete_tag_memory,
    detach_tag,
    ensure_default_severity,
    get_default_severity_tag_id,
    get_tag,
    get_tag_memory,
    list_session_ids_for_tag,
    list_session_tags,
    list_tags,
    put_tag_memory,
    session_has_severity_tag,
    update_tag,
)
from bearings.db._templates import (
    create_template,
    delete_template,
    get_template,
    list_templates,
)

__all__ = [
    "MIGRATIONS_DIR",
    "MoveResult",
    "ReorgOp",
    "add_session_cost",
    "append_tool_output",
    "attach_tag",
    "attach_tool_calls_to_message",
    "close_session",
    "create_artifact",
    "create_checklist",
    "create_checkpoint",
    "create_item",
    "create_session",
    "create_tag",
    "create_template",
    "delete_artifact",
    "delete_checkpoint",
    "delete_item",
    "delete_session",
    "delete_reorg_audit",
    "delete_tag",
    "delete_tag_memory",
    "delete_template",
    "detach_tag",
    "detect_tool_call_group_warnings",
    "ensure_default_severity",
    "find_replayable_prompt",
    "finish_tool_call",
    "get_artifact",
    "get_checklist",
    "get_checkpoint",
    "get_default_severity_tag_id",
    "get_item",
    "get_item_by_chat_session",
    "get_latest_todowrite",
    "get_session",
    "get_session_token_totals",
    "get_tag",
    "get_tag_memory",
    "get_template",
    "import_session",
    "init_db",
    "insert_message",
    "insert_tool_call_start",
    "is_checklist_complete",
    "list_all_messages",
    "list_all_sessions",
    "list_all_tool_calls",
    "list_artifacts",
    "list_checkpoints",
    "list_messages",
    "list_reorg_audits",
    "list_session_ids_for_tag",
    "list_session_tags",
    "list_sessions",
    "list_tags",
    "list_templates",
    "list_tool_calls",
    "mark_replay_attempted",
    "mark_session_completed",
    "mark_session_viewed",
    "move_messages_tx",
    "put_tag_memory",
    "record_reorg_audit",
    "reopen_if_closed",
    "reopen_session",
    "reorder_items",
    "search_messages",
    "session_has_severity_tag",
    "set_item_chat_session",
    "set_sdk_session_id",
    "set_session_context_usage",
    "set_session_permission_mode",
    "toggle_item",
    "touch_session",
    "update_checklist",
    "update_item",
    "update_message_flags",
    "update_session",
    "update_tag",
]
